// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Aggregate-function registration.
//!
//! Phase 3c (2026-06-24): wired via rusqlite's
//! `Connection::create_aggregate_function`. Each shim
//! AggregateFunctionDef becomes one ShimAggregate instance
//! registered under every canonical + alias name.
//!
//! State plumbing:
//!   - rusqlite's Aggregate<A, T> trait: A is the per-group
//!     accumulator type, T is the SQL return value (must
//!     impl ToSql). We use A = AccState (newtype around
//!     Box<dyn Accumulator>) and T = ToSqlOutput<'static>.
//!   - rusqlite requires A: RefUnwindSafe + UnwindSafe. The
//!     shim's Accumulator trait doesn't promise either, so
//!     AccState manually opts in (correctness rests on the
//!     shim not panicking on accumulate/finalize — its
//!     wasm-side impl uses Result, no unwinds expected).

use std::panic::{RefUnwindSafe, UnwindSafe};
use std::sync::Arc;

use rusqlite::functions::{Aggregate, Context, FunctionFlags};
use rusqlite::types::{ToSqlOutput, Value};
use rusqlite::{Connection, Result};

use datafission_functions::traits::{Accumulator, AggregateFunctionDef};
use datafission_functions::types::FunctionValue;

use crate::registry;
use crate::scalars::{function_value_to_tosql, value_ref_to_function_value};

/// Per-group accumulator state with the UnwindSafe opt-in that
/// rusqlite requires on `A`.
struct AccState(Box<dyn Accumulator>);
impl RefUnwindSafe for AccState {}
impl UnwindSafe for AccState {}

/// Stateless dispatcher: the per-group state lives in `AccState`,
/// not in this struct. One instance per (name × registration).
struct ShimAggregate {
    def: Arc<dyn AggregateFunctionDef>,
}

impl Aggregate<AccState, ToSqlOutput<'static>> for ShimAggregate {
    fn init(&self, _ctx: &mut Context<'_>) -> Result<AccState> {
        Ok(AccState(self.def.create_accumulator()))
    }

    fn step(&self, ctx: &mut Context<'_>, acc: &mut AccState) -> Result<()> {
        // PostGIS aggregates are unary (ST_Union, ST_Extent,
        // ST_Collect — all take one geometry). For multi-arg
        // future aggregates: walk every ctx arg and call
        // accumulate per row's input tuple. The Accumulator
        // trait takes one value per accumulate call.
        let n = ctx.len();
        if n == 0 {
            return Ok(());
        }
        let v = ctx.get_raw(0);
        // NULL convention: SQL-92 aggregates skip NULL inputs
        // (except COUNT(*)). The shim's Accumulator may also
        // skip; pass NULL through and let the shim decide.
        let value = value_ref_to_function_value(v);
        acc.0.accumulate(&value).map_err(|e| {
            rusqlite::Error::UserFunctionError(Box::new(
                std::io::Error::other(format!("{e:?}"))
            ))
        })
    }

    fn finalize(
        &self,
        _ctx: &mut Context<'_>,
        acc: Option<AccState>,
    ) -> Result<ToSqlOutput<'static>> {
        match acc {
            Some(a) => {
                let result = a.0.finalize().map_err(|e| {
                    rusqlite::Error::UserFunctionError(Box::new(
                        std::io::Error::other(format!("{e:?}"))
                    ))
                })?;
                Ok(function_value_to_tosql(result))
            }
            None => {
                // No rows accumulated → SQL aggregates return NULL.
                // (Except COUNT, which would return 0 — but that
                // never reaches this branch in practice.)
                let _ = self;
                let _ = FunctionValue::Null;
                Ok(ToSqlOutput::Owned(Value::Null))
            }
        }
    }
}

/// Register every aggregate the shim publishes.
pub fn register_all(conn: &Connection) -> Result<()> {
    register_aggregate(conn, "tbool_and_all_agg", 1)?;
    register_aggregate(conn, "tbool_any", 1)?;
    register_aggregate(conn, "tbool_count_false_agg", 1)?;
    register_aggregate(conn, "tbool_count_true_agg", 1)?;
    register_aggregate(conn, "tbool_every", 1)?;
    register_aggregate(conn, "tbool_or_all_agg", 1)?;
    register_aggregate(conn, "tbool_temporal_and", 1)?;
    register_aggregate(conn, "tand", 1)?; // alias of tbool_temporal_and
    register_aggregate(conn, "tbool_temporal_or", 1)?;
    register_aggregate(conn, "tor", 1)?; // alias of tbool_temporal_or
    register_aggregate(conn, "tcbuffer_temporal_count", 1)?;
    register_aggregate(conn, "tfloat_avg", 1)?;
    register_aggregate(conn, "tfloat_avg_agg", 1)?;
    register_aggregate(conn, "tfloat_count_agg", 1)?;
    register_aggregate(conn, "tfloat_max_agg", 1)?;
    register_aggregate(conn, "tfloat_max_value_agg", 1)?;
    register_aggregate(conn, "tfloat_median_agg", 1)?;
    register_aggregate(conn, "tfloat_min_agg", 1)?;
    register_aggregate(conn, "tfloat_min_value_agg", 1)?;
    register_aggregate(conn, "tfloat_range_agg", 1)?;
    register_aggregate(conn, "tfloat_stddev", 1)?;
    register_aggregate(conn, "tfloat_stddev_agg", 1)?;
    register_aggregate(conn, "tfloat_sum", 1)?;
    register_aggregate(conn, "tfloat_temporal_avg", 1)?;
    register_aggregate(conn, "tavg", 1)?; // alias of tfloat_temporal_avg
    register_aggregate(conn, "tfloat_temporal_count", 1)?;
    register_aggregate(conn, "tcount", 1)?; // alias of tfloat_temporal_count
    register_aggregate(conn, "tfloat_temporal_max", 1)?;
    register_aggregate(conn, "tmax", 1)?; // alias of tfloat_temporal_max
    register_aggregate(conn, "tfloat_temporal_min", 1)?;
    register_aggregate(conn, "tmin", 1)?; // alias of tfloat_temporal_min
    register_aggregate(conn, "tfloat_temporal_sum", 1)?;
    register_aggregate(conn, "tsum", 1)?; // alias of tfloat_temporal_sum
    register_aggregate(conn, "tfloat_total", 1)?;
    register_aggregate(conn, "tfloat_variance_agg", 1)?;
    register_aggregate(conn, "tgeogpoint_temporal_count", 1)?;
    register_aggregate(conn, "tgeompoint_centroid_agg", 1)?;
    register_aggregate(conn, "tgeompoint_num_convoys", 4)?;
    register_aggregate(conn, "tgeompoint_num_flocks", 3)?;
    register_aggregate(conn, "tgeompoint_num_meetings", 3)?;
    register_aggregate(conn, "tgeompoint_st_extent", 1)?;
    register_aggregate(conn, "tgeompoint_temporal_centroid", 1)?;
    register_aggregate(conn, "tgeompoint_temporal_count", 1)?;
    register_aggregate(conn, "tint_count_agg", 1)?;
    register_aggregate(conn, "tint_max_agg", 1)?;
    register_aggregate(conn, "tint_max_value_agg", 1)?;
    register_aggregate(conn, "tint_min_agg", 1)?;
    register_aggregate(conn, "tint_min_value_agg", 1)?;
    register_aggregate(conn, "tint_range_agg", 1)?;
    register_aggregate(conn, "tint_sum", 1)?;
    register_aggregate(conn, "tint_sum_agg", 1)?;
    register_aggregate(conn, "tint_temporal_max", 1)?;
    register_aggregate(conn, "tint_temporal_min", 1)?;
    register_aggregate(conn, "tint_temporal_sum", 1)?;
    register_aggregate(conn, "tnpoint_temporal_count", 1)?;
    register_aggregate(conn, "tpose_temporal_count", 1)?;
    register_aggregate(conn, "ttext_concat_agg", 1)?;
    register_aggregate(conn, "ttext_count_agg", 1)?;
    register_aggregate(conn, "ttext_max_agg", 1)?;
    register_aggregate(conn, "ttext_min_agg", 1)?;
    register_aggregate(conn, "ttext_string_agg", 1)?;
    // Phase 3c: 54 canonical + 7 alias names registered.
    Ok(())
}

fn register_aggregate(conn: &Connection, sql_name: &str, arity: i32) -> Result<()> {
    let def = registry::lookup_aggregate(sql_name).ok_or_else(|| {
        rusqlite::Error::UserFunctionError(
            format!("aggregate `{sql_name}` not registered by the shim").into()
        )
    })?;
    conn.create_aggregate_function(
        sql_name,
        arity,
        FunctionFlags::SQLITE_DETERMINISTIC | FunctionFlags::SQLITE_UTF8,
        ShimAggregate { def },
    )
}
