// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! CAST(x AS T) rewrites.
//!
//! ## Phase 4d — same blocker as operators.
//!
//! SQLite's `CAST(x AS GEOMETRY)` is parser-level — the type
//! name is consumed as a built-in token and converted at parse
//! time. There is no hook for a custom-type CAST. We cannot
//! rewrite `CAST(x AS GEOMETRY)` → `st_geomfromtext(x)` from
//! inside a loadable extension; the parse fails first.
//!
//! The proper home for cast rewrites is the same separate
//! `sqlink-preprocess` crate documented in operators.rs.

use rusqlite::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Cast rewrites the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// CAST(<castsourcekind::stringliteral> AS bitemporal_bool) → bitemporal_bool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_float) → bitemporal_float_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_int) → bitemporal_int_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_text) → bitemporal_text_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS datespan) → datespan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS datespanset) → datespanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspan) → floatspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspanset) → floatspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspan) → intspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspanset) → intspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox) → stbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox3d) → stbox3d_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool_sequence) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbox) → tbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer_sequence) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS textset) → textset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat_sequence) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint_sequence) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d_sequence) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint_sequence) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint_sequence) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint_sequence) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose_sequence) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspan) → tstzspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspanset) → tstzspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext) → ttext_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext_sequence) → ttext_from_ewkt (hint: )
