// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Operator handling.
//!
//! ## Phase 4d — ARCHITECTURALLY BLOCKED for a loadable
//! extension (2026-06-24)
//!
//! Operators like `g1 && g2` and `g1 <-> g2` are PARSER-LEVEL
//! tokens in PostgreSQL. SQLite's parser does not recognise
//! them — `SELECT g1 && g2` is a syntax error BEFORE any
//! function dispatch could intervene. There is no SQLite C
//! API to register a custom operator token.
//!
//! Loadable extensions cannot fix this. The bridge can register
//! a normal scalar function under any name, but the SQL parser
//! is fixed.
//!
//! ## Where this work actually lives
//!
//! Operator/cast/preprocessor support is a SQL-PREPROCESSING
//! concern, not an extension concern. The proper home is a
//! separate `sqlink-preprocess` crate that:
//!
//!   - Parses the SQL surface (via sqlparser-rs)
//!   - Rewrites operators: `g1 && g2` → `st_bboxintersects(g1, g2)`
//!   - Rewrites casts:     `CAST(x AS GEOMETRY)` → `st_geomfromtext(x)`
//!     when x is a string literal
//!   - Hands the rewritten SQL to rusqlite's `prepare`/`execute`
//!
//! That crate doesn't ship as a SQLite extension — it's a host-
//! side library users wrap their SQL with. It can absolutely be
//! generated from the same `BridgePlan` this crate emits, but
//! it's a separate target crate.
//!
//! ## The bridge-side compromise
//!
//! For users who don't want to wrap their SQL, the bridge could
//! register the operator NAMES as regular scalars under encoded
//! names:
//!
//!   register_scalar("op_amp_amp",   ...) → st_bboxintersects
//!   register_scalar("op_arrow",     ...) → st_knndistance
//!   register_scalar("op_at_gt",     ...) → st_contains
//!
//! Users write `op_amp_amp(g1, g2)` instead of `g1 && g2`. It
//! works (a function with that name is fine in SQLite) but it's
//! syntactically ugly. Not currently emitted — flip on by
//! removing the early return below.

use rusqlite::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    // Bridge-side compromise (op_<encoded>(args)) is deliberately
    // off by default. The proper home is sqlink-preprocess (a
    // separate sibling crate that wraps SQL before execute).
    Ok(())
}

// ----------------------------------------------------------------------
// Operators the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// `&&` (lhs=Some(3012), rhs=Some(3012))  →  intspan_overlaps
// `&&` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_overlaps
// `&&` (lhs=Some(3014), rhs=Some(3014))  →  datespan_overlaps
// `&&` (lhs=Some(3015), rhs=Some(3015))  →  temporal_overlaps
// `&&` (lhs=Some(3021), rhs=Some(3021))  →  intspanset_overlaps
// `&&` (lhs=Some(3022), rhs=Some(3022))  →  floatspanset_overlaps
// `&&` (lhs=Some(3023), rhs=Some(3023))  →  datespanset_overlaps
// `&&` (lhs=Some(3025), rhs=Some(3025))  →  stbox_overlaps
// `-|-` (lhs=Some(3015), rhs=Some(3015))  →  temporal_meets
// `<<` (lhs=Some(3015), rhs=Some(3015))  →  temporal_precedes
// `<<|` (lhs=Some(3015), rhs=Some(3015))  →  temporal_starts
// `<@` (lhs=Some(3015), rhs=Some(3015))  →  temporal_during
// `>>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_follows
// `@` (lhs=Some(3001), rhs=None)  →  tfloat_value_at
// `@` (lhs=Some(3002), rhs=None)  →  tint_value_at
// `@` (lhs=Some(3003), rhs=None)  →  tbool_value_at
// `@` (lhs=Some(3004), rhs=None)  →  ttext_value_at
// `@>` (lhs=Some(3012), rhs=None)  →  intspan_contains
// `@>` (lhs=Some(3012), rhs=Some(3012))  →  intspan_contains_span
// `@>` (lhs=Some(3013), rhs=None)  →  floatspan_contains
// `@>` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_contains_span
// `@>` (lhs=Some(3014), rhs=None)  →  datespan_contains
// `@>` (lhs=Some(3014), rhs=Some(3014))  →  datespan_contains_span
// `@>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_contains
// `@>` (lhs=Some(3021), rhs=Some(3021))  →  intspanset_contains_span
// `@>` (lhs=Some(3022), rhs=Some(3022))  →  floatspanset_contains_span
// `@>` (lhs=Some(3023), rhs=Some(3023))  →  datespanset_contains_span
// `@>` (lhs=Some(3025), rhs=Some(3025))  →  stbox_contains
// `|>>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_finishes
// `~=` (lhs=Some(3012), rhs=Some(3012))  →  intspan_adjacent
// `~=` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_adjacent
// `~=` (lhs=Some(3014), rhs=Some(3014))  →  datespan_adjacent
