// === GENERATED by sqlink-shim-codegen — do not edit by hand ===

//! Custom column types.
//!
//! SQLite does NOT have first-class custom types; the
//! conventional pattern is BLOB columns + a sidecar text-type
//! affinity. GEOMETRY ends up stored as EWKB blobs.
//!
//! The bridge advertises the type names so application code
//! can use `CREATE TABLE t (g GEOMETRY)` syntactically — but
//! SQLite stores it as BLOB. Type-id round-trips through the
//! shim are preserved via the shim's own type tag inside the
//! blob payload.

// type_id= 3001 name=TFLOAT_SEQUENCE          size=  -1  cast_from=[]  cast_to=[]
// type_id= 3002 name=TINT_SEQUENCE            size=  -1  cast_from=[]  cast_to=[]
// type_id= 3003 name=TBOOL_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3004 name=TTEXT_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3005 name=TGEOMPOINT_SEQUENCE      size=  -1  cast_from=[]  cast_to=[]
// type_id= 3006 name=TGEOGPOINT_SEQUENCE      size=  -1  cast_from=[]  cast_to=[]
// type_id= 3007 name=TGEOMPOINT3D_SEQUENCE    size=  -1  cast_from=[]  cast_to=[]
// type_id= 3008 name=TGEOMETRY_SEQUENCE       size=  -1  cast_from=[]  cast_to=[]
// type_id= 3009 name=TCBUFFER_SEQUENCE        size=  -1  cast_from=[]  cast_to=[]
// type_id= 3010 name=TPOSE_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3011 name=TNPOINT_SEQUENCE         size=  -1  cast_from=[]  cast_to=[]
// type_id= 3012 name=INTSPAN                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3013 name=FLOATSPAN                size=  -1  cast_from=[]  cast_to=[]
// type_id= 3014 name=DATESPAN                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3015 name=TSTZSPAN                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3016 name=INTSET                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 3017 name=FLOATSET                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3018 name=DATESET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3019 name=TSTZSET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3020 name=TEXTSET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3021 name=INTSPANSET               size=  -1  cast_from=[]  cast_to=[]
// type_id= 3022 name=FLOATSPANSET             size=  -1  cast_from=[]  cast_to=[]
// type_id= 3023 name=DATESPANSET              size=  -1  cast_from=[]  cast_to=[]
// type_id= 3024 name=TSTZSPANSET              size=  -1  cast_from=[]  cast_to=[]
// type_id= 3025 name=STBOX                    size=  48  cast_from=[]  cast_to=[]
// type_id= 3026 name=TBOX                     size=  32  cast_from=[]  cast_to=[]
// type_id= 3027 name=STBOX3D                  size=  56  cast_from=[]  cast_to=[]
// type_id= 3028 name=BITEMPORAL_BOOL          size=  -1  cast_from=[]  cast_to=[]
// type_id= 3029 name=BITEMPORAL_INT           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3030 name=BITEMPORAL_FLOAT         size=  -1  cast_from=[]  cast_to=[]
// type_id= 3031 name=BITEMPORAL_TEXT          size=  -1  cast_from=[]  cast_to=[]

// TODO: no explicit registration needed for SQLite — types are advisory.
//       Use this list to wire CAST() rewrites in casts.rs.
